### ISSUE TITLE
Wallet.send on Testnet.  66: rate limited free transaction. Code:-26

### ISSUE THREAD

**Issue by bobio2018** [qtumproject/qtumjs-wallet#17]
trying to use the wallet.send example with TESTNET, sender address definitely has fund.
```
const toAddress = "blah"
const amount = 0.15 * 1e8 // 0.15 QTUM
const tx = await wallet.send(toAddress, amount)
console.log(tx)
```
I notice it sends twice to https://testnet.qtum.org/insight-api/tx/send, first one Request:Options return a 204. The second one is Post with rawdata return as 400.
``` Error 66: rate limited free transaction. Code:-26```

Post data
```
{"rawtx":"0100000001931e4d68fffb1044d006a6099dc2123cfc52fc8cc3f3e502f51eb79106b0bfaa010000006b483045022100aa390eff8a634d95b111a2819c97236ebdc5705db58bcc3d4073ded86625c417022036d2f1bb46bb6a1b8c4d719451bca4a8261a5c924b33490eb6024fa270d4deaf0121021a33e5fc09e5db0a4ecce189916b813354e4c23f285ba7dc2dc555cf2e55361dffffffff020065cd1d000000001976a914d18b9005f2b370cc882a0c7c60d6414999bdf06188ac19525183010000001976a9144bd8573f65d633d84e59dbb02060f3b26cdbceb388ac00000000"}
```

**Comment by scriptfans** [comment]
@bobio2018 Are you using the web browser to run the example? If so, I guess the first option request was CORS "[preflight](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Functional_overview)".

`Error 66: rate limited free transaction. Code:-26`

Regarding this bug, we will deal with it as soon as possible.

**Comment by bobio2018** [comment]
@scriptfans yes I use Qtumjs-wallet in my react app, which is run in web browser, not from server backend. thank you so much for looking into this issue.

**Comment by bobio2018** [comment]
Update - adjust feeRate to 20000, it is working now. prelight still exist, but second request returns 200.

So probably need to adjust default feeRate in documentation
