### ISSUE TITLE
use gasLimit and gasPrice in contractSend cause error "Could not find UTXOs to build transaction"

### ISSUE THREAD

**Issue by bobio2018** [qtumproject/qtumjs-wallet#23]
On testnet, If I use gasLimit and gasPrice in generateContractSendTx 
```
const rawtx = await wallet.generateContractSendTx(contractAddress, encodedData, {
  amount: 0.01 * 1e8,
  gasLimit: 0.0000005,
  gasPrice: 3000000
})
```
and then use `wallet.contractSend` it throws an error Could not find UTXOs to build transaction
in /src/WalletRPCProvider.ts I can see it is using default 0.0000004 and 2500000.

Just wondering if we can use gasLimit and gasPrice for contract send?

Edit: thanks to @xuanyan0x7c7 I swap the gasLimit and gasPrice, still got the same error
```
const rawtx = await wallet.generateContractSendTx(contractAddress, encodedData, {
  amount: 0.01 * 1e8,
  gasLimit: 2500000,
  gasPrice: 0.0000004
})
```

**Comment by xuanyan0x7c7** [comment]
try swapping the value of gaslimit and gasprice

**Comment by bobio2018** [comment]
thanks @xuanyan0x7c7 I swap the gasLimit and gasPrice, still got the same error

**Comment by bobio2018** [comment]
@hayeah thanks, issue is solved
