### ISSUE TITLE
contractSend with multiple input parameters issue

### ISSUE THREAD

**Issue by qcoreprotocol** [qtumproject/qtumjs-wallet#41]
Hi, 
I am trying the **wallet.contractSend** function and run into some issues. It did send the tx however the result is not changed if I use wallet.contractSend function from this library, however it does work if I send to the contract using Qtum Desktop wallet.

I deployed a [QRC20 token](https://github.com/QcoreProtocolOrg/qcoreprotocol/blob/master/contracts/QCash.sol#L45) to testnet, the contract is successfully deployed on testnet [contract](https://testnet.qtum.info/contract/030c8cb5fc00c57519024ec6061f998e4cad5bc6)  the contract ABI is [here](https://github.com/QcoreProtocolOrg/qcoreprotocol/blob/master/deployment/Testnet/QCash/abi)

So my testing is really simple. I want to call the **approve** function in this contract including two parameters
```
address spender = db2542c0f8aaf791d077006ee984ca77d84016e2
uint amount = 100000000000000
```
I am passing **address = db2542c0f8aaf791d077006ee984ca77d84016e2** which is a farming pool contract address I want to allow spending of my QRC20 token, and **amount = 100000000000000** (which equals to 1000000 Qtum)

I use [ethereumjs-abi](https://github.com/ethereumjs/ethereumjs-abi) library to encode my data, also I use [this websit](https://abi.hashex.org/#) to verify, I got the same result

```
095ea7b30000000000000000000000000000002982cb46fad9655d0b9c9d9c5eeba8ccce00000000000000000000000000000000000000000000000000005af3107a4000
```

So I use above parameters to construct the call

```
const contractAddress = '030c8cb5fc00c57519024ec6061f998e4cad5bc6';
const encodedData = '095ea7b30000000000000000000000000000002982cb46fad9655d0b9c9d9c5eeba8ccce00000000000000000000000000000000000000000000000000005af3107a4000';

 const option = {
      amount: 0, // do not need to send Qtum, not payable
      gasLimit: 250000,
      gasPrice: 40; // in Satoshi
    };

const tx = await wallet.contractSend(contractAddress, encodedData, option);

```
The call seems to be successful. I didn't get any error from the [tx](https://testnet.qtum.info/tx/b5e6f118e8304d8e30071426db579191ad5a3351539cc43095829297476d80d8)

However when I go to [allowance](https://github.com/QcoreProtocolOrg/qcoreprotocol/blob/master/contracts/QCash.sol#L42) function to check

```
address owner: 4bd8573f65d633d84e59dbb02060f3b26cdbceb3  // this is the hex value of my wallet account
address spender:  db2542c0f8aaf791d077006ee984ca77d84016e2 // this is the spender address we pass in approve call

```
I always got 0 for allowance. The result should be 100000000000000.  

If I use Qtum Desktop wallet to call the contract's approve function then use allowance to check, I can always find the expected result.  The [tx call](https://testnet.qtum.info/tx/ea1ef5b848ee8f04067b81b020163591042082f4ebedf174d65b01c9a1373608) from the wallet doesn't look different from the one I send from wallet.contractSend.

I have previously used wallet.contractSend with a payable function with no input parameters and it works. Not sure if someone has seen any similar issues using multiple parameters and encoded Data issues?

**Comment by hayeah** [comment]
your abi-encoded data for approve looks a bit weird 

```
095ea7b3
0000000000000000000000000000002982cb46fad9655d0b9c9d9c5eeba8ccce
00000000000000000000000000000000000000000000000000005af3107a4000
```

what is `0000000000000000000000000000002982cb46fad9655d0b9c9d9c5eeba8ccce` ? 

the second chunk should be the spender address, so the abi-encoded data should be like:

```
095ea7b3
000000000000000000000000db2542c0f8aaf791d077006ee984ca77d84016e2
00000000000000000000000000000000000000000000000000005af3107a4000
```

**Comment by qcoreprotocol** [comment]
hi @hayeah 
The second chunk should be spender address encoded value for **db2542c0f8aaf791d077006ee984ca77d84016e2**

I use https://abi.hashex.org/# and get the same result

<img width="885" alt="Screen Shot 2020-11-17 at 8 32 49 am" src="https://user-images.githubusercontent.com/72120397/99310862-c4bc6180-28af-11eb-87ce-9c45c9fcf26d.png">

**Comment by qcoreprotocol** [comment]
I just found if I use another online tool https://adibas03.github.io/online-ethereum-abi-encoder-decoder/#/encode
and manually type in low case **address**, I get your result instead 
```
000000000000000000000000db2542c0f8aaf791d077006ee984ca77d84016e2
```

<img width="793" alt="Screen Shot 2020-11-17 at 9 22 56 am" src="https://user-images.githubusercontent.com/72120397/99315283-88d8ca80-28b6-11eb-9c67-6fca9d84faf4.png">

However when I use [ethereumjs-abi](https://github.com/ethereumjs/ethereumjs-abi), I am still getting 
```
0000000000000000000000000000002982cb46fad9655d0b9c9d9c5eeba8ccce
```
my console log result looks like below, address and uint256 are low cases

<img width="522" alt="Screen Shot 2020-11-17 at 9 25 53 am" src="https://user-images.githubusercontent.com/72120397/99315731-3350ed80-28b7-11eb-9796-c1dc417a37fe.png">

**Comment by qcoreprotocol** [comment]
Just using below code from ethereum-abi will give me 
```
0000000000000000000000000000002982cb46fad9655d0b9c9d9c5eeba8ccce
```
code

```
var encoded = abi.rawEncode([ "address" ], [ "db2542c0f8aaf791d077006ee984ca77d84016e2" ])
console.log(encoded.toString('hex'));

```

**Comment by qcoreprotocol** [comment]
Fixed! the address need to add prefix 0x
```
var encoded = abi.rawEncode([ "address" ], [ "0xdb2542c0f8aaf791d077006ee984ca77d84016e2" ])
console.log(encoded.toString('hex'));

```
result
```
000000000000000000000000db2542c0f8aaf791d077006ee984ca77d84016e2

```


now I am able to call wallet js to send tx

thanks @hayeah for looking into this
