### ISSUE TITLE
yarn build fails to minify

### ISSUE THREAD

**Issue by Alexis-Falquier** [qtumproject/qtumjs-wallet#5]
Creating a react app for a chrome extension using qtumjs-wallet. yarn build returns a minify error:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

 	.../node_modules/qtumjs-wallet/lib/Insight.js:14 
```
Per the react github troubleshoot section:

Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

To resolve this:
Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled.

**Comment by Alexis-Falquier** [comment]
Update:

the error occurs for most if not all libraries not just insight.js meaning to be able to build a react app with qtumjs-wallet, all js libraries should be published pre-compiled to ES5

**Comment by hayeah** [comment]
maybe try this ES6 compatible minifier: https://github.com/babel/minify

if you'd like a minified bundled build, please open another issue.
